name: app
channels:
  - conda-forge
dependencies:
  - python=3.11
  - dlib=19.24.*
  - pip
  - pip:
      - streamlit
      - streamlit-webrtc>=0.47
      - opencv-python-headless>=4.8
      - imutils>=0.5.4
      - numpy>=1.23
      - av>=11.0.0
